services:
  # Backend: FastAPI Python Service
  - type: web
    name: freshgroup-backend
    env: python
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: mysql://user:password@host:port/dbname  # Replace with your MySQL connection string
      - key: SECRET_KEY
        value: your-secret-key

  # Frontend: React/Next.js Service
  - type: web
    name: freshgroup-frontend
    env: node
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: REACT_APP_API_URL
        value: https://freshgroup-backend.onrender.com

databases:
  - name: freshgroup-db
    plan: free
    region: oregon
